import { User, Course, Group, Task, Evaluation, Notification } from "@/types";

export const mockUsers: User[] = [
  {
    id: "prof1",
    name: "ผศ.ดร.สมชาย",
    role: "professor",
    groupIds: [],
    activeGroupId: null,
  },
  {
    id: "ta1",
    name: "TA สมหญิง",
    role: "ta",
    groupIds: [],
    activeGroupId: null,
  },
  {
    id: "ta2",
    name: "TA สมศักดิ์",
    role: "ta",
    groupIds: [],
    activeGroupId: null,
  },
  {
    id: "student1",
    name: "นายอนันต์ ใจดี",
    role: "student",
    groupIds: ["group1"],
    activeGroupId: "group1",
  },
  {
    id: "student2",
    name: "นางสาวมาลี สวยงาม",
    role: "student",
    groupIds: ["group1"],
    activeGroupId: "group1",
  },
  {
    id: "student3",
    name: "นายวิชัย เก่งมาก",
    role: "student",
    groupIds: ["group1"],
    activeGroupId: "group1",
  },
  {
    id: "student4",
    name: "นางสาวสุดา รักเรียน",
    role: "student",
    groupIds: ["group2"],
    activeGroupId: "group2",
  },
  {
    id: "student5",
    name: "นายประเสริฐ ขยันดี",
    role: "student",
    groupIds: ["group2"],
    activeGroupId: "group2",
  },
];

export const mockCourses: Course[] = [
  {
    id: "course1",
    name: "CS101 - Introduction to Programming",
    professorId: "prof1",
    taIds: ["ta1"],
  },
];

export const mockGroups: Group[] = [
  {
    id: "group1",
    courseId: "course1",
    name: "กลุ่มที่ 1",
    memberIds: ["student1", "student2", "student3"],
    invitedIds: [],
  },
  {
    id: "group2",
    courseId: "course1",
    name: "กลุ่มที่ 2",
    memberIds: ["student4", "student5"],
    invitedIds: [],
  },
];

export const mockTasks: Task[] = [
  {
    id: "task1",
    groupId: "group1",
    title: "วิเคราะห์ความต้องการระบบ",
    description: "รวบรวมและวิเคราะห์ความต้องการของผู้ใช้งาน",
    status: "done",
    assigneeIds: ["student1"],
    attachments: [
      { id: "att1", label: "เอกสารวิเคราะห์", url: "https://example.com/doc1" },
    ],
    dueDate: "2026-03-20",
    createdAt: "2026-03-01T09:00:00Z",
    manHours: 8,
    subTasks: [],
  },
  {
    id: "task2",
    groupId: "group1",
    title: "ออกแบบ Database Schema",
    description: "ออกแบบโครงสร้างฐานข้อมูลสำหรับระบบ",
    status: "in_progress",
    assigneeIds: ["student2"],
    attachments: [],
    dueDate: "2026-04-10",
    createdAt: "2026-03-05T10:00:00Z",
    manHours: 12,
    subTasks: [
      { id: "st1", title: "ออกแบบตาราง User", completed: true },
      { id: "st2", title: "ออกแบบตาราง Task", completed: false },
    ],
  },
  {
    id: "task3",
    groupId: "group1",
    title: "พัฒนา Frontend UI",
    description: "สร้าง UI components สำหรับหน้าหลัก",
    status: "todo",
    assigneeIds: ["student3"],
    attachments: [],
    dueDate: "2026-04-20",
    createdAt: "2026-03-10T11:00:00Z",
    manHours: 16,
    subTasks: [],
  },
  {
    id: "task4",
    groupId: "group1",
    title: "เขียน Unit Tests",
    description: "เขียนการทดสอบสำหรับ business logic",
    status: "todo",
    assigneeIds: [],
    attachments: [],
    dueDate: "2026-04-25",
    createdAt: "2026-03-15T12:00:00Z",
    manHours: null,
    subTasks: [],
  },
  {
    id: "task5",
    groupId: "group2",
    title: "ออกแบบ UI Mockup",
    description: "สร้าง mockup สำหรับแอปพลิเคชัน",
    status: "done",
    assigneeIds: ["student4"],
    attachments: [
      { id: "att2", label: "Figma Design", url: "https://figma.com/design" },
    ],
    dueDate: "2026-03-25",
    createdAt: "2026-03-02T09:00:00Z",
    manHours: 6,
    subTasks: [],
  },
  {
    id: "task6",
    groupId: "group2",
    title: "พัฒนา Backend API",
    description: "สร้าง REST API endpoints",
    status: "in_progress",
    assigneeIds: ["student5"],
    attachments: [],
    dueDate: "2026-04-15",
    createdAt: "2026-03-08T10:00:00Z",
    manHours: 20,
    subTasks: [],
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: "eval1",
    groupId: "group1",
    evaluatorId: "student1",
    evaluateeId: "student2",
    score: 4,
    comment: "ทำงานได้ดี มีความรับผิดชอบสูง",
    submittedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "eval2",
    groupId: "group1",
    evaluatorId: "student1",
    evaluateeId: "student3",
    score: 5,
    comment: "เก่งมาก ช่วยเหลือเพื่อนตลอดเวลา",
    submittedAt: "2026-04-01T10:30:00Z",
  },
  {
    id: "eval3",
    groupId: "group1",
    evaluatorId: "student2",
    evaluateeId: "student1",
    score: 3,
    comment: "ทำงานได้ปานกลาง",
    submittedAt: "2026-04-02T09:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    userId: "student1",
    type: "task_assigned",
    message: "คุณได้รับมอบหมายงาน: วิเคราะห์ความต้องการระบบ",
    read: true,
    createdAt: "2026-03-01T09:00:00Z",
    meta: { groupId: "group1", taskId: "task1" },
  },
  {
    id: "notif2",
    userId: "student2",
    type: "task_assigned",
    message: "คุณได้รับมอบหมายงาน: ออกแบบ Database Schema",
    read: false,
    createdAt: "2026-03-05T10:00:00Z",
    meta: { groupId: "group1", taskId: "task2" },
  },
  {
    id: "notif3",
    userId: "student3",
    type: "eval_reminder",
    message: "กรุณาประเมินสมาชิกในกลุ่มก่อนสิ้นสุดภาคเรียน",
    read: false,
    createdAt: "2026-04-01T08:00:00Z",
    meta: { groupId: "group1" },
  },
  {
    id: "notif4",
    userId: "prof1",
    type: "invite_response",
    message: "นายอนันต์ ใจดี ได้ยอมรับคำเชิญเข้ากลุ่มที่ 1",
    read: false,
    createdAt: "2026-03-01T10:00:00Z",
    meta: { groupId: "group1" },
  },
];
