import { User, Workspace, Project, Team, Task, Evaluation, Notification, Meeting, UserProfile } from "@/types";

export const mockUsers: User[] = [
  { id: "user1", name: "นายอนันต์ ใจดี" },
  { id: "user2", name: "นางสาวมาลี สวยงาม" },
  { id: "user3", name: "นายวิชัย เก่งมาก" },
  { id: "user4", name: "นางสาวสุดา รักเรียน" },
  { id: "user5", name: "นายประเสริฐ ขยันดี" },
];

export const mockWorkspaces: Workspace[] = [
  {
    id: "ws1",
    name: "CS101 - ระบบจัดการโปรเจกต์",
    ownerId: "user1",
    adminIds: ["user2"],
    createdAt: "2026-03-01T00:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj1",
    workspaceId: "ws1",
    name: "โปรเจกต์กลางภาค",
    description: "โปรเจกต์สำหรับการประเมินกลางภาค",
    adminIds: [],
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "proj2",
    workspaceId: "ws1",
    name: "โปรเจกต์ปลายภาค",
    description: "โปรเจกต์สำหรับการประเมินปลายภาค",
    adminIds: [],
    createdAt: "2026-03-15T00:00:00Z",
  },
];

export const mockTeams: Team[] = [
  {
    id: "team1",
    projectId: "proj1",
    workspaceId: "ws1",
    name: "ทีม Alpha",
    members: [
      { userId: "user1", role: "team_leader" },
      { userId: "user2", role: "assistant_leader" },
      { userId: "user3", role: "member" },
    ],
    invitedIds: ["user4"],
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "team2",
    projectId: "proj1",
    workspaceId: "ws1",
    name: "ทีม Beta",
    members: [
      { userId: "user4", role: "team_leader" },
      { userId: "user5", role: "member" },
    ],
    invitedIds: [],
    createdAt: "2026-03-02T00:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task1",
    teamId: "team1",
    title: "วิเคราะห์ความต้องการระบบ",
    description: "รวบรวมและวิเคราะห์ความต้องการของผู้ใช้งาน",
    status: "done",
    assigneeIds: ["user1"],
    attachments: [
      { id: "att1", label: "เอกสารวิเคราะห์", url: "https://example.com/doc1" },
    ],
    dueDate: "2026-03-20",
    createdAt: "2026-03-01T09:00:00Z",
    manHours: 8,
    subTasks: [],
  },
  {
    id: "task2",
    teamId: "team1",
    title: "ออกแบบ Database Schema",
    description: "ออกแบบโครงสร้างฐานข้อมูลสำหรับระบบ",
    status: "in_progress",
    assigneeIds: ["user2"],
    attachments: [],
    dueDate: "2026-04-10",
    createdAt: "2026-03-05T10:00:00Z",
    manHours: 10,
    subTasks: [
      { id: "st1", title: "ออกแบบตาราง User", completed: true, manHours: 4, assigneeIds: ["user2"] },
      { id: "st2", title: "ออกแบบตาราง Task", completed: false, manHours: 6, assigneeIds: ["user1"] },
    ],
  },
  {
    id: "task3",
    teamId: "team1",
    title: "พัฒนา Frontend UI",
    description: "สร้าง UI components สำหรับหน้าหลัก",
    status: "todo",
    assigneeIds: ["user3"],
    attachments: [],
    dueDate: "2026-04-20",
    createdAt: "2026-03-10T11:00:00Z",
    manHours: null,
    subTasks: [
      { id: "st3", title: "สร้าง Navbar Component", completed: false, manHours: 3, assigneeIds: ["user3"] },
      { id: "st4", title: "สร้าง Dashboard Layout", completed: false, manHours: 5, assigneeIds: ["user3"] },
      { id: "st5", title: "สร้าง Task Card Component", completed: false, manHours: 4, assigneeIds: ["user1", "user3"] },
    ],
  },
  {
    id: "task4",
    teamId: "team1",
    title: "เขียน Unit Tests",
    description: "เขียนการทดสอบสำหรับ business logic",
    status: "todo",
    assigneeIds: [],
    attachments: [],
    dueDate: "2026-04-25",
    createdAt: "2026-03-15T12:00:00Z",
    manHours: null,
    subTasks: [],
  },
  {
    id: "task5",
    teamId: "team2",
    title: "ออกแบบ UI Mockup",
    description: "สร้าง mockup สำหรับแอปพลิเคชัน",
    status: "done",
    assigneeIds: ["user4"],
    attachments: [
      { id: "att2", label: "Figma Design", url: "https://figma.com/design" },
    ],
    dueDate: "2026-03-25",
    createdAt: "2026-03-02T09:00:00Z",
    manHours: 6,
    subTasks: [],
  },
  {
    id: "task6",
    teamId: "team2",
    title: "พัฒนา Backend API",
    description: "สร้าง REST API endpoints",
    status: "in_progress",
    assigneeIds: ["user5"],
    attachments: [],
    dueDate: "2026-04-15",
    createdAt: "2026-03-08T10:00:00Z",
    manHours: null,
    subTasks: [
      { id: "st6", title: "สร้าง Authentication API", completed: true, manHours: 8, assigneeIds: ["user5"] },
      { id: "st7", title: "สร้าง Task API", completed: false, manHours: 6, assigneeIds: ["user5"] },
      { id: "st8", title: "สร้าง Team API", completed: false, manHours: 6, assigneeIds: ["user4", "user5"] },
    ],
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: "eval1",
    teamId: "team1",
    evaluatorId: "user1",
    evaluateeId: "user2",
    score: 4,
    criteriaScores: {
      contribution: 4,
      qualityOfWork: 4,
      responsibility: 5,
      communication: 4,
      teamwork: 4,
      effort: 3,
    },
    comment: "ทำงานได้ดี มีความรับผิดชอบสูง",
    submittedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "eval2",
    teamId: "team1",
    evaluatorId: "user1",
    evaluateeId: "user3",
    score: 5,
    criteriaScores: {
      contribution: 5,
      qualityOfWork: 5,
      responsibility: 5,
      communication: 5,
      teamwork: 5,
      effort: 5,
    },
    comment: "เก่งมาก ช่วยเหลือเพื่อนตลอดเวลา",
    submittedAt: "2026-04-01T10:30:00Z",
  },
  {
    id: "eval3",
    teamId: "team1",
    evaluatorId: "user2",
    evaluateeId: "user1",
    score: 3,
    criteriaScores: {
      contribution: 3,
      qualityOfWork: 3,
      responsibility: 4,
      communication: 3,
      teamwork: 3,
      effort: 2,
    },
    comment: "ทำงานได้ปานกลาง",
    submittedAt: "2026-04-02T09:00:00Z",
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "meeting1",
    teamId: "team1",
    topic: "ประชุมวางแผนโปรเจกต์",
    description: "หารือเรื่องการแบ่งงานและ timeline ของโปรเจกต์",
    attendeeIds: ["user1", "user2", "user3"],
    link: "https://meet.google.com/abc-defg-hij",
    datetime: "2026-04-10T14:00:00Z",
    notificationSettings: [
      { id: "ns1", minutesBefore: 1440, label: "1 วันก่อน" },
      { id: "ns2", minutesBefore: 60, label: "1 ชั่วโมงก่อน" },
    ],
    createdBy: "user1",
    createdAt: "2026-04-05T09:00:00Z",
  },
  {
    id: "meeting2",
    teamId: "team1",
    topic: "รีวิว Database Schema",
    description: "ตรวจสอบและแก้ไข schema ที่ออกแบบไว้",
    attendeeIds: ["user1", "user2"],
    link: "https://zoom.us/j/1234567890",
    datetime: "2026-04-15T10:00:00Z",
    notificationSettings: [
      { id: "ns3", minutesBefore: 180, label: "3 ชั่วโมงก่อน" },
    ],
    createdBy: "user2",
    createdAt: "2026-04-06T08:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    userId: "user1",
    type: "task_assigned",
    message: "คุณได้รับมอบหมายงาน: วิเคราะห์ความต้องการระบบ",
    read: true,
    createdAt: "2026-03-01T09:00:00Z",
    meta: { teamId: "team1", taskId: "task1" },
  },
  {
    id: "notif2",
    userId: "user2",
    type: "task_assigned",
    message: "คุณได้รับมอบหมายงาน: ออกแบบ Database Schema",
    read: false,
    createdAt: "2026-03-05T10:00:00Z",
    meta: { teamId: "team1", taskId: "task2" },
  },
  {
    id: "notif3",
    userId: "user3",
    type: "eval_reminder",
    message: "กรุณาประเมินสมาชิกในทีมก่อนสิ้นสุดภาคเรียน",
    read: false,
    createdAt: "2026-04-01T08:00:00Z",
    meta: { teamId: "team1" },
  },
  {
    id: "notif4",
    userId: "user4",
    type: "invitation",
    message: "คุณได้รับคำเชิญเข้าร่วมทีม Alpha",
    read: false,
    createdAt: "2026-03-01T10:00:00Z",
    meta: { teamId: "team1" },
  },
  {
    id: "notif5",
    userId: "user1",
    type: "meeting_reminder",
    message: "การประชุม 'ประชุมวางแผนโปรเจกต์' จะเริ่มใน 1 วัน",
    read: false,
    createdAt: "2026-04-09T14:00:00Z",
    meta: { teamId: "team1", meetingId: "meeting1" },
  },
  {
    id: "notif6",
    userId: "user2",
    type: "meeting_reminder",
    message: "การประชุม 'ประชุมวางแผนโปรเจกต์' จะเริ่มใน 1 วัน",
    read: false,
    createdAt: "2026-04-09T14:00:00Z",
    meta: { teamId: "team1", meetingId: "meeting1" },
  },
];

export const mockProfiles: UserProfile[] = [
  {
    userId: "user1",
    name: "อนันต์ ใจดี",
    firstName: "อนันต์",
    lastName: "ใจดี",
    bio: "นักศึกษาวิศวกรรมซอฟต์แวร์ ชอบทำ Full-stack development",
    contacts: [
      { type: "Email", value: "anan.jaidee@email.com" },
      { type: "Line", value: "anan_jaidee" },
    ],
    displayNames: { team1: "Anan" },
  },
  {
    userId: "user2",
    name: "มาลี สวยงาม",
    firstName: "มาลี",
    lastName: "สวยงาม",
    bio: "UX/UI Designer ที่รักในการออกแบบ",
    contacts: [
      { type: "Email", value: "malee.s@email.com" },
      { type: "IG", value: "@malee.design" },
    ],
    displayNames: { team1: "Malee" },
  },
  {
    userId: "user3",
    name: "วิชัย เก่งมาก",
    firstName: "วิชัย",
    lastName: "เก่งมาก",
    bio: "Backend developer สาย Java & Spring Boot",
    contacts: [
      { type: "Discord", value: "wichai#1234" },
    ],
    displayNames: {},
  },
  {
    userId: "user4",
    name: "สุดา รักเรียน",
    firstName: "สุดา",
    lastName: "รักเรียน",
    bio: "Data Science enthusiast",
    contacts: [
      { type: "Email", value: "suda.rakrian@email.com" },
    ],
    displayNames: { team2: "Suda" },
  },
  {
    userId: "user5",
    name: "ประเสริฐ ขยันดี",
    firstName: "ประเสริฐ",
    lastName: "ขยันดี",
    bio: "DevOps & Cloud infrastructure",
    contacts: [
      { type: "Email", value: "prasert.k@email.com" },
      { type: "Phone", value: "081-234-5678" },
    ],
    displayNames: {},
  },
];
